from enum import Enum

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    UniqueConstraint,
    func,
    inspect,
    text,
)

# use postgres primitives
from sqlalchemy.dialects.postgresql import BOOLEAN, JSONB, TEXT, TIMESTAMP, UUID
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    declared_attr,
    mapped_column,
    relationship,
)
from sqlalchemy.sql.expression import false


class Base(DeclarativeBase):
    def to_dict(self):
        """Instance method to convert model columns to a dictionary."""
        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}


class OrgUserRole(Enum):
    OWNER = "owner"
    ADMIN = "admin"
    EDITOR = "editor"
    READER = "reader"


class _BaseModel(Base):
    __abstract__ = True
    # make all ids a random uuid generated by the db
    id: Mapped[str] = mapped_column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    created_at: Mapped[DateTime] = mapped_column(TIMESTAMP, nullable=False, server_default=func.now())
    updated_at: Mapped[DateTime] = mapped_column(
        TIMESTAMP, nullable=False, server_default=func.now(), onupdate=func.now()
    )
    created_by_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    updated_by_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    @declared_attr
    def created_by(cls) -> Mapped["User"]:
        return relationship(
            "User",
            foreign_keys=[cls.created_by_id],
            remote_side="User.id",
            backref=f"created_{cls.__tablename__}",
        )

    @declared_attr
    def updated_by(cls) -> Mapped["User"]:
        return relationship(
            "User",
            foreign_keys=[cls.updated_by_id],
            remote_side="User.id",
            backref=f"updated_{cls.__tablename__}",
        )


class User(_BaseModel):
    __tablename__ = "users"
    name: Mapped[str] = mapped_column(TEXT)
    email: Mapped[str] = mapped_column(TEXT, unique=True, nullable=False)
    email_verified: Mapped[bool] = mapped_column(BOOLEAN, nullable=False, server_default=false())
    password_hash: Mapped[str] = mapped_column(TEXT, nullable=False)
    is_admin: Mapped[bool] = mapped_column(BOOLEAN, nullable=False, server_default=false())


class Org(_BaseModel):
    __tablename__ = "orgs"
    name: Mapped[str] = mapped_column(TEXT, nullable=False)
    charter: Mapped[str] = mapped_column(TEXT, nullable=True)


class OrgSettings(_BaseModel):
    __tablename__ = "org_settings"
    __table_args__ = (UniqueConstraint("org_id", "setting_name"),)
    org_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("orgs.id"), nullable=False)
    org: Mapped["Org"] = relationship("Org", backref="settings")
    setting_name: Mapped[str] = mapped_column(TEXT, nullable=False)
    setting_value: Mapped[str] = mapped_column(TEXT, nullable=True)


class OrgUser(_BaseModel):
    __tablename__ = "org_users"
    org_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("orgs.id"), nullable=False)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    org: Mapped["Org"] = relationship("Org", backref="users")
    user: Mapped["User"] = relationship("User", foreign_keys=[user_id], backref="orgs")
    role: Mapped[str] = mapped_column(TEXT, nullable=False)  # e.g., 'admin', 'member', etc.


class RssFeed(_BaseModel):
    __tablename__ = "rss_feeds"
    org_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("orgs.id"), nullable=False)
    org: Mapped[Org] = relationship("Org", backref="rss_feeds")
    url: Mapped[str] = mapped_column(TEXT, nullable=False)
    title: Mapped[str] = mapped_column(TEXT, nullable=True)
    last_fetched_at: Mapped[DateTime] = mapped_column(TIMESTAMP, nullable=True)
    active: Mapped[bool] = mapped_column(BOOLEAN, nullable=False, server_default=false())


class Artifact(_BaseModel):
    __tablename__ = "artifacts"
    __table_args__ = (Index("ix_artifacts_type", "type"),)
    ref_table_name: Mapped[str] = mapped_column(nullable=False)
    ref_table_id: Mapped[str] = mapped_column(UUID(as_uuid=True), nullable=False)
    type: Mapped[str] = mapped_column(TEXT, nullable=False)
    data: Mapped[dict] = mapped_column(TEXT, nullable=False)


class Transformation(_BaseModel):
    __tablename__ = "transformations"
    artifact_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("artifacts.id"), nullable=False)
    artifact: Mapped["Artifact"] = relationship("Artifact", backref="transformations")
    type: Mapped[str] = mapped_column(TEXT, nullable=False)
    context: Mapped[dict] = mapped_column(JSONB, nullable=True)
    result: Mapped[dict] = mapped_column(JSONB, nullable=True)
    metadata: Mapped[dict] = mapped_column(JSONB, nullable=True)


class RssFeedItem(_BaseModel):
    __tablename__ = "rss_feed_items"
    __table_args__ = (UniqueConstraint("feed_id", "dedup_key"),)
    feed_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("rss_feeds.id"), nullable=False)
    feed: Mapped["RssFeed"] = relationship("RssFeed", backref="items")
    dedup_key: Mapped[str] = mapped_column(TEXT, nullable=False)
    title: Mapped[str] = mapped_column(TEXT, nullable=False)
    link: Mapped[str] = mapped_column(TEXT, nullable=False)
    content: Mapped[str] = mapped_column(TEXT, nullable=True)
    # artifact_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("artifacts.id"), nullable=True)
    # artifact: Mapped[Artifact] = relationship("Artifact", backref="rss_feed_items", cascade="all, delete-orphan")


class AppSettings(_BaseModel):
    __tablename__ = "app_settings"
    __table_args__ = (UniqueConstraint("setting_name"),)
    setting_name: Mapped[str] = mapped_column(TEXT, nullable=False)
    setting_value: Mapped[str] = mapped_column(TEXT, nullable=True)


class WikiPage(_BaseModel):
    __tablename__ = "wiki_pages"
    org_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("orgs.id"), nullable=False)
    org: Mapped["Org"] = relationship("Org", backref="wiki_pages")
    title: Mapped[str] = mapped_column(TEXT, nullable=False)
    content: Mapped[str] = mapped_column(TEXT, nullable=True)


class WikiPageVersion(_BaseModel):
    __tablename__ = "wiki_page_versions"
    __table_args__ = (UniqueConstraint("page_id", "version_number"),)
    page_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("wiki_pages.id"), nullable=False)
    page: Mapped["WikiPage"] = relationship("WikiPage", backref="versions")
    version_number: Mapped[int] = mapped_column(nullable=False)
    content: Mapped[str] = mapped_column(TEXT, nullable=True)
