from enum import Enum
from typing import Any

from sqlalchemy import (
    DateTime,
    ForeignKey,
    UniqueConstraint,
    func,
    inspect,
    text,
)

# use postgres primitives
from sqlalchemy.dialects.postgresql import BOOLEAN, TEXT, TIMESTAMP, UUID
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    declared_attr,
    mapped_column,
    relationship,
)
from sqlalchemy.sql.expression import false


class Base(DeclarativeBase):
    def to_dict(self) -> dict[str, Any]:
        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}


class OrgUserRole(Enum):
    OWNER = "owner"
    ADMIN = "admin"
    EDITOR = "editor"
    READER = "reader"


class _BaseModel(Base):
    """Every row: a UUID id and created/updated timestamps. No authorship — the default base."""

    __abstract__ = True
    # make all ids a random uuid generated by the db
    id: Mapped[str] = mapped_column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    created_at: Mapped[DateTime] = mapped_column(TIMESTAMP, nullable=False, server_default=func.now())
    updated_at: Mapped[DateTime] = mapped_column(
        TIMESTAMP, nullable=False, server_default=func.now(), onupdate=func.now()
    )


class _AuthoredModel(_BaseModel):
    """Adds created_by/updated_by. Only for rows a user authors — never machine-generated data."""

    __abstract__ = True
    created_by_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    updated_by_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    @declared_attr
    def created_by(cls) -> Mapped["User"]:
        return relationship(
            "User",
            foreign_keys=[cls.created_by_id],  # type: ignore[list-item]  # declared_attr column, not str
            remote_side="User.id",
            backref=f"created_{cls.__tablename__}",
        )

    @declared_attr
    def updated_by(cls) -> Mapped["User"]:
        return relationship(
            "User",
            foreign_keys=[cls.updated_by_id],  # type: ignore[list-item]  # declared_attr column, not str
            remote_side="User.id",
            backref=f"updated_{cls.__tablename__}",
        )


class User(_AuthoredModel):
    __tablename__ = "users"
    name: Mapped[str] = mapped_column(TEXT)
    email: Mapped[str] = mapped_column(TEXT, unique=True, nullable=False)
    email_verified: Mapped[bool] = mapped_column(BOOLEAN, nullable=False, server_default=false())
    password_hash: Mapped[str] = mapped_column(TEXT, nullable=False)
    is_admin: Mapped[bool] = mapped_column(BOOLEAN, nullable=False, server_default=false())


class Org(_AuthoredModel):
    __tablename__ = "orgs"
    name: Mapped[str] = mapped_column(TEXT, nullable=False)
    charter: Mapped[str] = mapped_column(TEXT, nullable=True)


class OrgSettings(_AuthoredModel):
    __tablename__ = "org_settings"
    __table_args__ = (UniqueConstraint("org_id", "setting_name"),)
    org_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("orgs.id"), nullable=False)
    org: Mapped["Org"] = relationship("Org", backref="settings")
    setting_name: Mapped[str] = mapped_column(TEXT, nullable=False)
    setting_value: Mapped[str] = mapped_column(TEXT, nullable=True)


class OrgUser(_AuthoredModel):
    __tablename__ = "org_users"
    org_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("orgs.id"), nullable=False)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    org: Mapped["Org"] = relationship("Org", backref="users")
    user: Mapped["User"] = relationship("User", foreign_keys=[user_id], backref="orgs")
    role: Mapped[str] = mapped_column(TEXT, nullable=False)  # e.g., 'admin', 'member', etc.


class AppSettings(_AuthoredModel):
    __tablename__ = "app_settings"
    __table_args__ = (UniqueConstraint("setting_name"),)
    setting_name: Mapped[str] = mapped_column(TEXT, nullable=False)
    setting_value: Mapped[str] = mapped_column(TEXT, nullable=True)


class WikiPage(_AuthoredModel):
    __tablename__ = "wiki_pages"
    org_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("orgs.id"), nullable=False)
    org: Mapped["Org"] = relationship("Org", backref="wiki_pages")
    title: Mapped[str] = mapped_column(TEXT, nullable=False)
    content: Mapped[str] = mapped_column(TEXT, nullable=True)


class WikiPageVersion(_AuthoredModel):
    __tablename__ = "wiki_page_versions"
    __table_args__ = (UniqueConstraint("page_id", "version_number"),)
    page_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("wiki_pages.id"), nullable=False)
    page: Mapped["WikiPage"] = relationship("WikiPage", backref="versions")
    version_number: Mapped[int] = mapped_column(nullable=False)
    content: Mapped[str] = mapped_column(TEXT, nullable=True)
