from datetime import datetime
from enum import Enum
from typing import Any

from sqlalchemy import (
    ForeignKey,
    UniqueConstraint,
    func,
    inspect,
    text,
)

# use postgres primitives
from sqlalchemy.dialects.postgresql import ARRAY, BOOLEAN, JSONB, TEXT, TIMESTAMP, UUID
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    backref,
    declared_attr,
    mapped_column,
    relationship,
)
from sqlalchemy.sql.expression import false


class Base(DeclarativeBase):
    def to_dict(self) -> dict[str, Any]:
        return {c.key: getattr(self, c.key) for c in inspect(self).mapper.column_attrs}


class KnowledgeBaseUserRole(Enum):
    OWNER = "owner"
    ADMIN = "admin"
    EDITOR = "editor"
    READER = "reader"


class _BaseModel(Base):
    """Every row: a UUID id and created/updated timestamps. No authorship — the default base."""

    __abstract__ = True
    # make all ids a random uuid generated by the db
    id: Mapped[str] = mapped_column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, nullable=False, server_default=func.now(), onupdate=func.now()
    )


class _AuthoredModel(_BaseModel):
    """Adds created_by/updated_by. Only for rows a user authors — never machine-generated data."""

    __abstract__ = True
    created_by_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    updated_by_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)

    @declared_attr
    def created_by(cls) -> Mapped["User"]:
        return relationship(
            "User",
            foreign_keys=[cls.created_by_id],  # type: ignore[list-item]  # declared_attr column, not str
            remote_side="User.id",
            backref=f"created_{cls.__tablename__}",
        )

    @declared_attr
    def updated_by(cls) -> Mapped["User"]:
        return relationship(
            "User",
            foreign_keys=[cls.updated_by_id],  # type: ignore[list-item]  # declared_attr column, not str
            remote_side="User.id",
            backref=f"updated_{cls.__tablename__}",
        )


class User(_AuthoredModel):
    __tablename__ = "users"
    name: Mapped[str] = mapped_column(TEXT)
    email: Mapped[str] = mapped_column(TEXT, unique=True, nullable=False)
    email_verified: Mapped[bool] = mapped_column(BOOLEAN, nullable=False, server_default=false())
    password_hash: Mapped[str] = mapped_column(TEXT, nullable=False)
    is_admin: Mapped[bool] = mapped_column(BOOLEAN, nullable=False, server_default=false())


class KnowledgeBase(_AuthoredModel):
    __tablename__ = "knowledge_bases"
    name: Mapped[str] = mapped_column(TEXT, nullable=False)
    charter: Mapped[str] = mapped_column(TEXT, nullable=True)


class JobStatus(Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    DONE = "done"
    SKIPPED = "skipped"
    FAILED = "failed"


class KnowledgeBaseConfig(_BaseModel):
    __tablename__ = "knowledge_base_configs"
    __table_args__ = (UniqueConstraint("knowledge_base_id"),)
    knowledge_base_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("knowledge_bases.id"), nullable=False)
    knowledge_base: Mapped["KnowledgeBase"] = relationship("KnowledgeBase", backref=backref("config", uselist=False))
    relevance_prompt: Mapped[str] = mapped_column(TEXT, nullable=False)
    entity_types: Mapped[list[str]] = mapped_column(ARRAY(TEXT), nullable=False, server_default=text("'{}'"))
    relationship_types: Mapped[list[str]] = mapped_column(ARRAY(TEXT), nullable=False, server_default=text("'{}'"))


class ApiKey(_BaseModel):
    __tablename__ = "api_keys"
    knowledge_base_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("knowledge_bases.id"), nullable=False)
    knowledge_base: Mapped["KnowledgeBase"] = relationship("KnowledgeBase", backref="api_keys")
    key_hash: Mapped[str] = mapped_column(TEXT, nullable=False, unique=True)
    revoked_at: Mapped[datetime | None] = mapped_column(TIMESTAMP, nullable=True)
    name: Mapped[str | None] = mapped_column(TEXT, nullable=True)
    # First chars of the raw key, for masked display (the raw key itself is never stored).
    prefix: Mapped[str | None] = mapped_column(TEXT, nullable=True)
    last_used_at: Mapped[datetime | None] = mapped_column(TIMESTAMP, nullable=True)
    created_by_id: Mapped[str | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)


class AuthSession(_BaseModel):
    """A logged-in session. The `session` cookie holds an opaque token; only its sha256 is stored."""

    __tablename__ = "sessions"
    token_hash: Mapped[str] = mapped_column(TEXT, nullable=False, unique=True, index=True)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(TIMESTAMP, nullable=False)
    last_seen_at: Mapped[datetime | None] = mapped_column(TIMESTAMP, nullable=True)


class EmailToken(_BaseModel):
    """A single-use email link token (verification or password reset). The link carries an
    opaque token; only its sha256 is stored. `purpose` is 'verify' | 'reset'."""

    __tablename__ = "email_tokens"
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    purpose: Mapped[str] = mapped_column(TEXT, nullable=False)
    token_hash: Mapped[str] = mapped_column(TEXT, nullable=False, unique=True, index=True)
    expires_at: Mapped[datetime] = mapped_column(TIMESTAMP, nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(TIMESTAMP, nullable=True)


class IngestJob(_BaseModel):
    __tablename__ = "ingest_jobs"
    knowledge_base_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("knowledge_bases.id"), nullable=False)
    knowledge_base: Mapped["KnowledgeBase"] = relationship("KnowledgeBase", backref="ingest_jobs")
    content: Mapped[str] = mapped_column(TEXT, nullable=False)
    # `metadata` is reserved on Declarative classes, so the attribute is job_metadata.
    job_metadata: Mapped[dict[str, Any] | None] = mapped_column("metadata", JSONB, nullable=True)
    status: Mapped[str] = mapped_column(TEXT, nullable=False, server_default=JobStatus.PENDING.value)
    relevance_reason: Mapped[str | None] = mapped_column(TEXT, nullable=True)
    error: Mapped[str | None] = mapped_column(TEXT, nullable=True)
    attempts: Mapped[int] = mapped_column(nullable=False, server_default=text("0"))
    processed_at: Mapped[datetime | None] = mapped_column(TIMESTAMP, nullable=True)


class KnowledgeBaseUser(_AuthoredModel):
    __tablename__ = "knowledge_base_users"
    knowledge_base_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("knowledge_bases.id"), nullable=False)
    user_id: Mapped[str] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    knowledge_base: Mapped["KnowledgeBase"] = relationship("KnowledgeBase", backref="users")
    user: Mapped["User"] = relationship("User", foreign_keys=[user_id], backref="knowledge_bases")
    role: Mapped[str] = mapped_column(TEXT, nullable=False)  # e.g., 'admin', 'member', etc.
