"""claims tables

Revision ID: a4c26bd6f186
Revises: 
Create Date: 2026-07-27 00:25:07.211519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4c26bd6f186'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims_documents',
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('canonical_url', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('full_text', sa.TEXT(), nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reported_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url', name='claims_documents_canonical_url')
    )
    op.create_table('claims_claims',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('quote', sa.TEXT(), nullable=True),
    sa.Column('attributed_to', sa.TEXT(), nullable=True),
    sa.Column('attribution_type', sa.TEXT(), nullable=True),
    sa.Column('cited_source', sa.TEXT(), nullable=True),
    sa.Column('cited_source_url', sa.TEXT(), nullable=True),
    sa.Column('claim_type', sa.TEXT(), nullable=False),
    sa.Column('checkworthiness', sa.REAL(), nullable=False),
    sa.Column('selected_for_verification', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('verdict', sa.TEXT(), nullable=True),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('rationale', sa.TEXT(), nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['claims_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims_reports',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('path', sa.TEXT(), nullable=False),
    sa.Column('claim_count', sa.INTEGER(), nullable=False),
    sa.Column('verified_count', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['claims_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims_evidence',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('snippet', sa.TEXT(), nullable=True),
    sa.Column('stance', sa.TEXT(), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims_evidence')
    op.drop_table('claims_reports')
    op.drop_table('claims_claims')
    op.drop_table('claims_documents')
    # ### end Alembic commands ###
