"""add_transform_runs_and_position

Revision ID: 33cdb7d6b31a
Revises: 38c497f97185
Create Date: 2026-07-22 18:22:21.963142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33cdb7d6b31a'
down_revision: Union[str, Sequence[str], None] = '38c497f97185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transform_runs',
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('input_artifact_id', sa.UUID(), nullable=False),
    sa.Column('output_artifact_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default='pending', nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['input_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['output_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transformations', sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_unique_constraint(None, 'transformations', ['org_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transformations', type_='unique')
    op.drop_column('transformations', 'position')
    op.drop_table('transform_runs')
    # ### end Alembic commands ###
