"""split_authored_base_model

Revision ID: 759f45082ea2
Revises: fa2d0e17a383
Create Date: 2026-07-22 19:57:28.482486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759f45082ea2'
down_revision: Union[str, Sequence[str], None] = 'fa2d0e17a383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artifacts_updated_by_id_fkey'), 'artifacts', type_='foreignkey')
    op.drop_constraint(op.f('artifacts_created_by_id_fkey'), 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'created_by_id')
    op.drop_column('artifacts', 'updated_by_id')
    op.drop_constraint(op.f('rss_feed_items_created_by_id_fkey'), 'rss_feed_items', type_='foreignkey')
    op.drop_constraint(op.f('rss_feed_items_updated_by_id_fkey'), 'rss_feed_items', type_='foreignkey')
    op.drop_column('rss_feed_items', 'created_by_id')
    op.drop_column('rss_feed_items', 'updated_by_id')
    op.drop_constraint(op.f('transform_runs_updated_by_id_fkey'), 'transform_runs', type_='foreignkey')
    op.drop_constraint(op.f('transform_runs_created_by_id_fkey'), 'transform_runs', type_='foreignkey')
    op.drop_column('transform_runs', 'created_by_id')
    op.drop_column('transform_runs', 'updated_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transform_runs', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transform_runs', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('transform_runs_created_by_id_fkey'), 'transform_runs', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('transform_runs_updated_by_id_fkey'), 'transform_runs', 'users', ['updated_by_id'], ['id'])
    op.add_column('rss_feed_items', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('rss_feed_items', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('rss_feed_items_updated_by_id_fkey'), 'rss_feed_items', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(op.f('rss_feed_items_created_by_id_fkey'), 'rss_feed_items', 'users', ['created_by_id'], ['id'])
    op.add_column('artifacts', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('artifacts', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('artifacts_created_by_id_fkey'), 'artifacts', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('artifacts_updated_by_id_fkey'), 'artifacts', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###
