"""add_artifact_org_and_item_status

Revision ID: fa2d0e17a383
Revises: 33cdb7d6b31a
Create Date: 2026-07-22 19:20:31.442808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2d0e17a383'
down_revision: Union[str, Sequence[str], None] = '33cdb7d6b31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'artifacts', 'orgs', ['org_id'], ['id'])
    op.add_column('rss_feed_items', sa.Column('status', sa.TEXT(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_feed_items', 'status')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_column('artifacts', 'org_id')
    # ### end Alembic commands ###
