"""issue body

Revision ID: 62d1dbefaf4f
Revises: a84fff8c6230
Create Date: 2026-07-25 20:49:39.521339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d1dbefaf4f'
down_revision: Union[str, Sequence[str], None] = 'a84fff8c6230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neonews_issues', sa.Column('body', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('neonews_issues', 'body')
    # ### end Alembic commands ###
