"""neonews tables

Revision ID: a84fff8c6230
Revises: 
Create Date: 2026-07-25 16:33:09.461828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a84fff8c6230'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neonews_issues',
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('covers_since', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('path', sa.TEXT(), nullable=False),
    sa.Column('story_count', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neonews_job_state',
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('ran_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('neonews_sources',
    sa.Column('kind', sa.TEXT(), nullable=False),
    sa.Column('locator', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_polled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('failure_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'locator', name='neonews_sources_kind_locator')
    )
    op.create_table('neonews_items',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('full_text', sa.TEXT(), nullable=True),
    sa.Column('job_id', sa.TEXT(), nullable=True),
    sa.Column('job_status', sa.TEXT(), nullable=True),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['neonews_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'dedup_key', name='neonews_items_source_dedup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neonews_items')
    op.drop_table('neonews_sources')
    op.drop_table('neonews_job_state')
    op.drop_table('neonews_issues')
    # ### end Alembic commands ###
